# Generated by Django 4.0.4 on 2022-04-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('сontrol_type', models.CharField(max_length=200)),
                ('lector', models.CharField(max_length=200)),
                ('lector_isu', models.CharField(max_length=200)),
                ('content_lectures', models.TextField()),
                ('practice', models.CharField(max_length=200)),
                ('practice_isu', models.CharField(max_length=200)),
                ('content_practice', models.TextField()),
                ('deadlines', models.TextField()),
            ],
        ),
    ]
