# Generated by Django 4.0.4 on 2022-07-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_subject_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('patronymic', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lector',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lector_isu',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='practice_isu',
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.CharField(max_length=25),
        ),
    ]
